services:
  api:
    build:
      context: .
    image: fastapi-task-api:learning
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/tasks.db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - fastapi-task-data:/data
    restart: unless-stopped

  redis:
    image: redis:8.10.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped


volumes:
  fastapi-task-data:
    external: true